### ISSUE TITLE
Call to non-static member function without an object argument

### ISSUE THREAD

**Issue by kraxarn** [kiswa/SFML_Starter#2]
How do you actually use loadFont and loadTexture?
To be "very simple", it's not very easy to use.
Some examples or documentation would be nice.

**Comment by kiswa** [comment]
The file `game_state.cpp` has an example of both (lines 10 & 11).

It's "very simple" as in not a lot of complexity. You still have to know how to use SFML.

For documentation, see [SFML](http://www.sfml-dev.org/) and the README - that's really all there is to this project. It's just a very basic setup to use SFML for game development.

If you have any ideas for improvement, PRs are always welcome.
